benjaminkott/bootstrap_package

Documentation/Configuration/TypoScript/Index.rst

pissible -> possible and others

Fix typos in Index.rst

---

Configuration/ContentElements/Base.ts

fixed "incomplete" tags  in lib.newsheader

Bugfix in  Base.ts

---

.gitignore
Configuration/TypoScript/setup.txt
Resources/Private/Layouts/Page/Default.html
Resources/Private/Partials/Page/Navigation/Main.html
Resources/Private/Partials/Page/Structure/Footer.html
Resources/Private/Templates/Page/Default2Columns.html
Resources/Private/Templates/Page/Default2Columns2575.html
Resources/Private/Templates/Page/Default2Columns5050.html
Resources/Private/Templates/Page/Default2ColumnsOffsetRight.html
Resources/Private/Templates/Page/Default3Columns.html
Resources/Private/Templates/Page/DefaultSubNavLeft.html
Resources/Private/Templates/Page/DefaultSubNavLeft2Columns.html
Resources/Private/Templates/Page/DefaultSubNavRight.html
Resources/Private/Templates/Page/DefaultSubNavRight2Columns.html

Hi Benjamin,
our first results of the html5 improvements for the introduction package are ready for review / merge.

html5 improvements

---

Configuration/TypoScript/constants.txt
Configuration/TypoScript/setup.txt
Resources/Private/Partials/Page/Navigation/Main.html

[BUGFIX] fix for HTML5 markup validation

---

Resources/Private/Language/Backend.xlf

Added description for Text and Icon, Carousel, Acordion, Panel and List Group

[TASK] Added missing description to Bootstrap elements

---

Classes/UserFunc/Typo3VersionCondition.php
Classes/Utility/TemplateFileResolver.php
Configuration/TypoScript/setup.txt

checked with typo3 6.2.13 and typo3 7.3.0 which includes support for templateRootPaths.

FLUIDTEMPLATE.templateName and templateRootPaths

---

Configuration/TypoScript/setup.txt

[BUGFIX] Use correct assignment for TypoScript value

---

Classes/Hooks/RealUrl/AutoConfig.php
Classes/Service/CompileService.php
Classes/Service/InstallService.php
Classes/UserFunc/TemplateFileResolver.php
Classes/ViewHelpers/DataRelationViewHelper.php
Configuration/TCA/Overrides/tt_content.php
Configuration/TCA/Overrides/tx_bootstrappackage_carousel_item.php
Configuration/TCA/tx_bootstrappackage_carousel_item.php
ext_emconf.php
ext_localconf.php

@benjaminkott requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/benjaminkott/bootstrap_package/

Scrutinizer Auto-Fixes

---

Configuration/PageTS/RTE.txt

Add the table colspan and rowspan attributes to allowed attributes in RTE configuration

[BUGFIX] Add the table colspan and rowspan attributes

---

Documentation/Introduction/Index.rst

Maybe some different entry was intended?

Remove duplicate "List Group" entry

---

.gitignore
.php_cs
Classes/DataProcessing/MenuProcessor.php
Classes/Service/CompileService.php
Classes/Service/InstallService.php
Classes/Utility/ExternalMediaUtility.php
Classes/ViewHelpers/ContextualClassViewHelper.php
Classes/ViewHelpers/DataRelationViewHelper.php
Classes/ViewHelpers/ExplodeViewHelper.php
Classes/ViewHelpers/ExternalMediaViewHelper.php
Classes/ViewHelpers/FalViewHelper.php
Classes/ViewHelpers/VarViewHelper.php
Configuration/TCA/Overrides/pages.php
Configuration/TCA/Overrides/tt_content.php
ext_localconf.php
ext_tables.php

This change just reformats the code according to the CGL with the following command:
```
php-cs-fixer fix --config-file .php_cs
```

[TASK] Fix Code according to CGL

---

.travis.yml

To be able to judge changes to the assets, we should build them out on travis

[TASK] Test asset pipe on travis

---

Classes/DataProcessing/MenuProcessor.php
Resources/Private/Partials/Page/Navigation/Breadcrumb.html
Resources/Private/Partials/Page/Navigation/Main.html
Resources/Private/Partials/Page/Navigation/Subnavigation.html

See text of these commit messages
* d7cb557 [BUGFIX] Do not use f:format.raw() for 'title' any more
* 629679c [TASK] Adjust PHPDOC comment
* 3a3f99b [BUGFIX] Do proper JSON encoding of 'title'

[BUGFIX] Bugfix/menuprocessor

---

Configuration/TypoScript/setup.txt

By using pagelayout, the proper template is chosen

[BUGFIX] Use correct layout

---

Documentation/AdministratorManual/Migration/6-2-11.rst

if you are not usind the theme
==> using

"usind" is wrong

---

README.rst

[TASK] Add instruction to clear initial TypoScript

---

Configuration/TypoScript/Helper/DynamicContent.txt

Relates to https://forge.typo3.org/issues/81492
and https://forge.typo3.org/issues/80506

[BUGFIX] Prepare colPos field for proper quoting

---

Configuration/TypoScript/setup.txt

Fix typoscript og:image height to avoid error

BP_6-2 fix og:image setup height

---

Configuration/TypoScript/setup.typoscript
Resources/Private/Partials/Page/Navigation/Language.html

Ich hab recht fix language menu

---

ext_localconf.php

Fixes # .
Fixed Typo in ext_localconf

[BUGFIX] fixed typo

---

.gitignore

Adds the NetBeans IDE project directory to the ignore file. Closes #539.

Closes #539

---

Classes/Parser/AbstractParser.php

changed classname from BrandingService to AbstractParser

[CLEANUP] Correct class comment in abstract parser

---

Configuration/TypoScript/ContentElement/Helper/ContentElement.typoscript

[!!!][BUGFIX] Use correct constant for texticon width

---

Classes/Parser/LessParser.php
Classes/Parser/ScssParser.php

[BUGFIX] Include autoloader for parser class check

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/support.md
.github/PULL_REQUEST_TEMPLATE.md

This patch streamlines the issue and pull request templates.

[TASK] Update issue and pull request templates

---

Configuration/TsConfig/Page/TCEMAIN.tsconfig

[TASK] Remove deprecated translateToHidden option

---

README.rst

[DOCS] Add links to Wiki and Documentation

---

Build/Gruntfile.js

Fixes #789 
Steps to verify:
- delete Resources/Public/Fonts
- run `yarn build`
- verify all files are created and no one is missing

[TASK] Change build order

---

Contrib/scssphp/bin/pscss
Contrib/scssphp/composer.json
Contrib/scssphp/src/Cache.php
Contrib/scssphp/src/Compiler.php
Contrib/scssphp/src/Formatter.php
Contrib/scssphp/src/Formatter/Nested.php
Contrib/scssphp/src/Parser.php
Contrib/scssphp/src/SourceMap/Base64VLQ.php
Contrib/scssphp/src/Version.php
Tests/Unit/Scss/Fixtures/Calculation.css
Tests/Unit/Scss/Fixtures/Calculation.scss
Tests/Unit/Scss/ScssTest.php
composer.json

[BUGFIX] Conflict scssphp/scssphp 1.0.4 and 1.0.5 for composer installs

---

Classes/Service/BrandingService.php

See https://review.typo3.org/c/Packages/TYPO3.CMS/+/62650
Closes #835
Related FriendsOfTYPO3/introduction#30, FriendsOfTYPO3/introduction#31

[TASK] Remove path in ExtensionConfiguration::set call

---

Configuration/TCA/tx_bootstrappackage_accordion_item.php
Configuration/TCA/tx_bootstrappackage_card_group_item.php
Configuration/TCA/tx_bootstrappackage_carousel_item.php
Configuration/TCA/tx_bootstrappackage_icon_group_item.php
Configuration/TCA/tx_bootstrappackage_tab_item.php
Configuration/TCA/tx_bootstrappackage_timeline_item.php

[BUGFIX] Ensure correct field casing and escaping in TCA for database compatibility

---

composer.json

[BUGFIX] Add missing filter extension dependency

---

Classes/Controller/ContentController.php
Configuration/TypoScript/ContentElement/Element/Gallery.typoscript
ext_localconf.php

[BUGFIX] Change controllerActionName in extbase configuration of gallery

---

Classes/Service/GoogleFontService.php

See deprecation #90956 (https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-90956-AlternativeFetchMethodsAndReportsForGeneralUtilitygetUrl.html) and feature #70056 (https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.1/Feature-70056-GuzzleForHttpRequests.html)
This patch can be used down to version 8 of Bootstrap Package.

[TASK] Replace GeneralUtility::getUrl by RequestFactory

---

Resources/Public/Scss/Theme/_tables.scss
Resources/Public/Scss/Theme/theme.scss

[BUGFIX] Introduce table-condensed class again for compatibility

---

.github/workflows/check-pr.yml

The Check PR workflow now also listens to edit, ready_for_review and review_requested events.

[TASK] Update pull request types for Check PR workflow

---

composer.json

Ensure stable core versions are prefered by default for development.

[TASK] Reintroduce prefer-stable

---

Classes/Backend/ToolbarItem/VersionToolbarItem.php
Classes/Service/BrandingService.php
Configuration/Services.yaml
ext_localconf.php

See feature #90249 (https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-90249-NewPSR-14EventsForExistingPackage-relatedSignalSlots.html)

[TASK] Migrate signals to PSR-14 events

---

Documentation/AdministratorManual/Migration/6-2-11.rst

calculation

---

.github/workflows/ci.yml

[TASK] Allow tests to pass for phpstan and build result for now

---

Configuration/TCA/Overrides/200_content_element_accordion.php
Configuration/TCA/Overrides/203_content_element_card_group.php
Configuration/TCA/Overrides/210_content_element_icon_group.php
Configuration/TCA/Overrides/221_content_element_tab.php
Configuration/TCA/Overrides/229_content_element_timeline.php
Configuration/TCA/Overrides/300_content_general_columns.php

This TCA option is not used by the core since v7 anymore.

[TASK] Remove all showRemovedLocalizationRecords occurrences

---

Build/phpstan-baseline.neon
Build/phpstan.neon
Classes/Updates/AccordionContentElementUpdate.php
Classes/Updates/AccordionMediaOrientUpdate.php
Classes/Updates/BackendLayoutUpdate.php
Classes/Updates/BulletContentElementUpdate.php
Classes/Updates/CarouselContentElementUpdate.php
Classes/Updates/CarouselItemLayoutUpdate.php
Classes/Updates/CarouselItemTypeUpdate.php
Classes/Updates/ExternalMediaContentElementUpdate.php
Classes/Updates/FrameClassToBackgroundUpdate.php
Classes/Updates/FrameClassUpdate.php
Classes/Updates/ListGroupContentElementUpdate.php
Classes/Updates/PanelContentElementUpdate.php
Classes/Updates/TabContentElementUpdate.php
Classes/Updates/TabMediaOrientUpdate.php
Classes/Updates/TableContentElementUpdate.php
Classes/Updates/TexticonContentElementUpdate.php
Classes/Updates/TexticonIconUpdate.php
Classes/Updates/TexticonSizeUpdate.php
Classes/Updates/TexticonTypeUpdate.php

[REVERT][BUGFIX] Update doctrine usages (#1037)

---

composer.json

[TASK] Update branch alias

---

Resources/Private/Templates/ContentElements/CarouselFullscreen.html
Resources/Private/Templates/ContentElements/CarouselSmall.html

[BUGFIX] Add Bootstrap v5 options to Fullscreen and Small carousel

---

Classes/Updates/CarouselContentElementUpdate.php

Closes #568
Closes #569
Releases:

[BUGFIX] Preserve custom layout values

---

.ddev/config.yaml

This makes sure the binaries can be found e.g. for the typo3 custom
command.

[TASK] Add .build/bin to $PATH

---

Resources/Private/Partials/Page/Navigation/Subnavigation.html

[TASK] Exclude submenues from indexing

---

Documentation/Settings.cfg

[BUGFIX] Docs rendering

---

Resources/Private/Forms/Contact.form.yaml

See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-80420-AllowMultipleRecipientsInEmailFinisher.html

[TASK] Migrate form definition

---

Contrib/scssphp/bin/pscss
Contrib/scssphp/composer.json
Contrib/scssphp/src/Compiler.php
Contrib/scssphp/src/Node/Number.php
Contrib/scssphp/src/Version.php
composer.json

[TASK] Update scssphp to v1.8.1

---

Classes/Updates/AccordionContentElementUpdate.php
Classes/Updates/AccordionMediaOrientUpdate.php
Classes/Updates/BackendLayoutUpdate.php
Classes/Updates/BulletContentElementUpdate.php
Classes/Updates/CarouselContentElementUpdate.php
Classes/Updates/CarouselItemLayoutUpdate.php
Classes/Updates/CarouselItemTypeUpdate.php
Classes/Updates/ExternalMediaContentElementUpdate.php
Classes/Updates/FrameClassToBackgroundUpdate.php
Classes/Updates/FrameClassToOptionsUpdate.php
Classes/Updates/FrameClassUpdate.php
Classes/Updates/ListGroupContentElementUpdate.php
Classes/Updates/PanelContentElementUpdate.php
Classes/Updates/TabContentElementUpdate.php
Classes/Updates/TabMediaOrientUpdate.php
Classes/Updates/TableContentElementUpdate.php
Classes/Updates/TexticonContentElementUpdate.php
Classes/Updates/TexticonIconUpdate.php
Classes/Updates/TexticonSizeUpdate.php
Classes/Updates/TexticonTypeUpdate.php

[BUGFIX] PHPStan issues

---

.gitattributes

* Documentation should be read online and the raw rest files are not extremely useful
* Tests should never be released

Exclude Tests folder for export

---

Configuration/TypoScript/constants.typoscript

Fixed typo: Wrong constant label

---

Classes/DataProcessing/ArrayProcessor.php
Classes/ViewHelpers/FrameViewHelper.php
Configuration/TypoScript/ContentElement/Helper/ContentElement.typoscript
Resources/Private/Layouts/ContentElements/Default.html
Resources/Private/Templates/ViewHelpers/Frame/Index.html

The bootstrap package ships a container around each and every content element that is 
used as a wrapper to control the behavior of the inner content. To have this aligned a 
view helper was introduced to reduce the complexity of the templates and have more 
simple temples while the calculation is done in PHP.
If you need to provide additional classes to the elements we provided an easy-to-extend
frame option to each and every content element. That also reduced the need to override
existing templates.
Still, extension authors also need the option to assign additional attributes to the wrapper.
This is mostly used in conjunction with JavaScript to provide data attributes to the element.
We are now extending the frame view helper with a new option frameAttributes. This 
option takes an …

[TASK] add additionalAttributes to FrameViewHelper

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/PULL_REQUEST_TEMPLATE.md

- Supported TYPO3 versions are 11 and 12
- Supported TYPO3 versions PHP 7.4 - 8.2

[DOCS] Adjust Templates for PRs and Issues

---

.github/workflows/ci.yml

[TASK] Enable functional tests for v12

---

.crowdin.yml

This pull request adds the necessary configuration for the Crowdin integration to translate all labels in the xlf files.

[TASK] Add Crowdin configuration file

---

Classes/ViewHelpers/ExplodeViewHelper.php
Classes/ViewHelpers/ImplodeViewHelper.php

Adopt viewhelper example code to prevent issues on copy and paste
This minor change is PHP comment only which fixes viewhelper documentation

feat: fix viewhelper documentation

---

Configuration/Sets/GoogleFont/setup.typoscript

Fix Google Fonts TypoScript path in site set
