- Classes/ViewHelpers/DataRelationViewHelper.php
- Classes/ViewHelpers/FalViewHelper.php
the render function in FalViewHelper.php is missing localization
-> localized background images in the Carousel are not shown in the frontend,
instead the background from the default language is shown.
the changes are "inspired" by sysext/frontend/Classes/Page/PageRepository.php
i am not sure if its needed to include the _PAGES_OVERLAY_UID check, that part may be omitted if the helper will never gets used on page like records.
> [Bugfix] fixes missing localization support in FalViewHelper.php

- Configuration/PageTS/RTE.txt
After 884dc4049c8fc21d0678f210aa13abb287ce13fc it's no more possible to specify the target of a link. This edit fixes this.
> Allow "target" attribute inside <a> tags.

- Classes/Service/CompileService.php
- Configuration/TypoScript/constants.txt
- Configuration/TypoScript/setup.txt
Hey @benjaminkott,
this is another patch (the last one) needed to use an external Less processor like Prepros.
This doesn't change the default behaviour of EXT:bootstrap_package but allows advanced users to set a constant to disable the use of Typoscript constants as Less variables.
In this case the user must customize the default Bootstrap variables directly in Less.
Related to:
https://github.com/benjaminkott/bootstrap_package/issues/162
https://github.com/benjaminkott/bootstrap_package/pull/168
> [FEATURE] New advanced constant to enable/disable the use of Typoscript constants as Less variables

- Configuration/PageTS/RTE.txt
The bootstrap package still uses xhtml cleaning. That currently gives this deprecation warning (thrown in HtmlParser):
*This section has been deprecated with TYPO3 CMS 7 and will be removed with CMS 8.*
This feature is superfluous nowadays, has been deprecated and is marked for removal from TYPO3 Core.
> Stop using deprecated XHTML cleaning

- Configuration/FlexForms/Carousel.xml
- Resources/Private/Language/Backend.xlf
- Resources/Private/Templates/ContentElements/Bootstrap/Carousel.html
Hi @benjaminkott,
this commit allow to set the max width (default 1920px) of background images in carousels BE form.
I think that this can be useful because an editor could upload an image too much big and, without a max width, this image will impact the download time of the page.
Also this option can be useful to limit the max width in other cases, by instance for small carousels.
It shouldn't hurt existing installation.
Let me know if you also find this useful.
Thanks!
> [TASK] Carousel: allow to set the max width of background images

- Classes/Service/CompileService.php
- Configuration/TypoScript/constants.txt
- Configuration/TypoScript/setup.txt
Hi @benjaminkott,
here is the rewrite of this feature (ref. https://github.com/benjaminkott/bootstrap_package/pull/168).
This feature enable CSS source mapping (https://developer.chrome.com/devtools/docs/css-preprocessors) very useful to debug the generated CSS from Less. It's enabled if new constant 'plugin.bootstrap_package.settings.cssSourceMapping = 1'. It will also automatically disable CSS compression.
> [FEATURE] New advanced constant to enable/disable CSS source mapping

- Resources/Public/JavaScript/Libs/jquery.responsiveimages.js
Hi everybody !
@benjaminkott  Your (or whoever does it) job on this plugin is awsome guys, it's a real pleasure to make some little enhancement 
Line 119  
Add .bk2k namespace to window.on(load) event
Allow re-init plugin when page content does change eg by ajax call. The event namespace is intentionnaly left without .responsiveimage
to allow scroll and resize events to be disabled before ajax content changes without killing the window.load event
```javascript
// Re-init plugin with new content after ajax call
$(window).trigger('load.bk2k');
// Remove events listeners before ajax call
$(window).off('bk2k.responsiveimage');
// Force images update on eg tab change, carousel change... 
$(window).trigger('scroll.bk2k.responsiveimage');
```
Line 84 
There is no more callback on image loaded …
> Fine tune jquery.responsiveimage.js

- Resources/Public/JavaScript/Libs/jquery.responsiveimages.js
As i am extending $.fn. with viewportH and viewportW methods, setting this.width and this.height into those methods does override jquery width and height methods ... too bad !
Using viewportWidth and viewportHeight as variable names does fix the conflict.
We may instantiate the viewport class out of the responsiveimage constructor, and use a setOptions method inside of the constructor,  but your way of doing it with if(viewport) seem mutch cleaner and simplier. so +1 for your solution.
> Fix collision with jQuery width and height methods

- Configuration/TypoScript/constants.txt
- Documentation/Configuration/TypoScript/Index.rst
I know this is pedantic, but i keep seeing these...
Can't help myself, I just had to propose a fix.
> Fix 'overridden' typos

- Configuration/TCA/Overrides/tt_content.php
this breaks the requestUpdate ctrl string in tt_content, see https://forge.typo3.org/issues/68517
> [BUGFIX] Use always $GLOBALS[TCA]

- class.ext_update.php
TYPO3 6.2 still runs on PHP 5.3/5.4. Using ::class is only
possible starting from PHP 5.5.
Resolves: #213
> [BUGFIX] Make class.ext_update.php work on PHP <5.5 as well

- Resources/Public/JavaScript/Libs/jquery.responsiveimages.js
Add js support to load all images before printing
Note : another option is to set a data-preload="true" attribute to your images.
```javascript
$(window).on("readytoprint.bk2k.responsiveimage", function(){
// images urls are ready to print
});
$(window).trigger("beforeprint.bk2k.responsiveimage");
```
> Force preload images to allow print

- class.ext_update.php
Add a namespace to the ext_update class to support installation via composer.
Without namespace composer will throw a warning about ambiguous class resolution.
```
Warning: Ambiguous class resolution, "ext_update" was found in both "$baseDir . '/typo3conf/ext/extension-a/class.ext_update.php" and /typo3conf/ext/extension-b/class.ext_update.php", the first will be used.
```
Similar errors exist in other extensions, see https://forge.typo3.org/issues/70541.
> [BUGFIX] Add namespace to ext_update class

- Configuration/TypoScript/constants.txt
- Configuration/TypoScript/setup.txt
Configurable through TS constant `config.sendCacheHeaders`
and through the constants editor.
Closes: #283
> [!!!][TASK] Send cache headers per default

- Configuration/PageTS/RTE.txt
The insertcharacter and findreplace buttons added here are in the htmlArea RTE's default "Typical" configuration, so editors may expect to see them.
> Add useful RTE buttons

- Configuration/TCA/Overrides/pages.php
- Resources/Private/Language/ExtConfTemplate.xlf
- ext_conf_template.txt
- ext_localconf.php
Modifies inclusion of
* tt_content previews
* new content element wizard items
in a form that either allows them to be included
via ext_typoscript_setup or not.
This is especially helpful with overrides and migration
paths of existing sites to the bootstrap_package.
> [FEATURE] Remaining PageTS templates are configurable

- Configuration/PageTS/RTE.txt
The list of allowed classes missed the "empty" element, which auto-fixed
not-allowed classes to get the first class assigned automatically.
Example:
```
RTE.default.proc.entryHTMLparser_db {
p.fixAttrib.class.list = lead, text-left, text-center
}
```
Source:
```
<p class="cool-legacy-class">..Bla..</p>
```
Will get cleaned up to
```
<p class="lead">..Bla..</p>
```
Adding the empty list-element fixes this faulty behaviour:
```
RTE.default.proc.entryHTMLparser_db {
p.fixAttrib.class.list = , lead, text-left, text-center
}
```
> [BUGFIX] Fix behaviour of strictly allowed RTE classes

- Resources/Private/Partials/Page/Navigation/Breadcrumb.html
- Resources/Private/Partials/Page/Navigation/Main.html
- Resources/Private/Partials/Page/Navigation/Subnavigation.html
Menu titles already get escaped by TypoScript in
\BK2K\BootstrapPackage\DataProcessing\MenuProcessor. This patch ensures
the tiles are used without escaping.
> [BUGFIX] Prevent double escaping of menu titles

- Configuration/TCA/Overrides/sys_template.php
- ext_tables.php
A new core check within the install tool will soon check for extensions
that still change TCA from within ext_tables.php files.
The patch fixes the last match in ext:bootstrap_package.
Related: #78384
> [BUGFIX] Move TCA change in ext_tables.php to TCA/Overrides

- Configuration/TypoScript/setup.txt
config.uniqueLinkVars has been removed in TYPO3 7.0
> [TASK] remove uniqueLinkVars

- Configuration/TCA/tx_bootstrappackage_accordion_item.php
- Configuration/TCA/tx_bootstrappackage_carousel_item.php
- Configuration/TCA/tx_bootstrappackage_tab_item.php
In the patch https://review.typo3.org/#/c/52061/1 TYPO3 v8 now setts correct sys_language_uid on child items, when adding them directly to translated parent (tt_content).
However this patch only works when sys_language_uid is in the showitem array.
This patch adds a hidden palette which language fields. The same solution is used in the core for FAL fields.
1. Add tt_content with acordeon item and translate it to language 1
2. see in db that translated items will have correct sys_language_uid set (1)
3. add new item to the translated tt_content
4. check in db that sys_language_uid of the child is 0
5. apply the patch, clear cache
6. redo step 3 and 4
7. see that sys_language_uid is set correctlt to 1
> [BUGFIX] Fix sys_language_uid when adding item to translated tt_content

- Configuration/TypoScript/ContentElement/MenuCategorizedContent.typoscript
If the table "sys_category_record_mm" is promoted to a 1st level table and gets a "uid" column, the menu "Content elements for selected categories" will throw an SQL error like this:
> Column 'uid' in on clause is ambiguous
Avoid this by explicitly prefixing the table name.
Fixes # .
> [TASK] Avoid ambiguous "uid" error

- .github/PULL_REQUEST_TEMPLATE.md
Using `--config-file` option returns errors, without everything is ok inclusive loading of the default config:
The "--config-file" option does not exist.
fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--diff-format DIFF-FORMAT] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>]...
> Wrong option

- Configuration/TypoScript/Bootstrap4/constants.typoscript
FIX wrong TS constant label.
* [X ] Changes have been tested on TYPO3 dev-master
The label for constant $primary is wrong ($secondary). This MR fixes that.
You can see this in constant editor.
> [BUGFIX] Correct primary label in bs4 typoscript constants

- Configuration/TypoScript/setup.typoscript
- Resources/Public/JavaScript/Dist/bootstrap.accordion.min.js
- Resources/Public/JavaScript/Src/bootstrap.accordion.js
Fixes #588 .
Add custom javascript to calulate position of expanded accordion entry.
This lets the window scroll to top of its content, when not in focus.
1. Create accordion content element with at least 2 entries, where the first entry has long text as content and second entry just a short content.
2. Open page with accordion, and open first entry
3. Scroll down and open second entry
4. Second accordion entry should scroll to top of window, so its content is visible at start
> [FEATURE] Collapsible in accordion should scroll to the top of content

- Contrib/less.php/Less.php
Fixes: #584
Replace `continue` with `continue 2` in less parser.
1. Install PHP 7.3
2. View Less Version of BP
3. Apply Patch: no more error.
> [BUGFIX] Make Less Parser PHP 7.3 compatible

- Configuration/TypoScript/ContentElement/Element/Uploads.typoscript
When creating a content element "File Links" [uploads] specifying the sorting direction desc is ignored.
> [BUGFIX] ce uploads accepts sorting direction

- Classes/ViewHelpers/InlineSvgViewHelper.php
The ImageService::getImage requires a string as first and a boolean as
third parameter. The Image ViewHelper must respect this requirement.
> [BUGFIX] Ensure type safety for ViewHelper calling ImageService

- Resources/Private/Partials/Form/Field/Field.html
see https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.7.x/Deprecation-84449-TranslateElementErrorViewHelperArguments.html
> [BUGFIX] Use error object in form field template

- Classes/ViewHelpers/File/IsAudioViewHelper.php
- Classes/ViewHelpers/File/IsImageViewHelper.php
- Classes/ViewHelpers/File/IsMediaViewHelper.php
- Resources/Private/Partials/ContentElements/Media/Type.html
- Resources/Private/Templates/ContentElements/Audio.html
- Resources/Private/Templates/ContentElements/Uploads.html
To deliver the best results possible, the bootstrap package
has a strict type checking before passing assets to the 
renderings. Even if your system was capable of rendering 
images from PDFs it was not allowed by default through 
those type checkings, since a PDF is in the mime-type 
group application. 
That means we were not able to simply allow these application 
group since that would also, mean that the system would try to 
generate an image from a zip file, like in fluid styled content.
Since there is still a huge demand for PDF previews, we made 
the decision to extend the current type checks. TYPO3 allows 
to configure imagefile_ext and mediafile_ext in its configuration. 
We are now also allowing the processing of files with extensions 
configured in the according to lists. …
> [FEATURE] Allow processing of configured file types

- Configuration/TypoScript/Bootstrap4/constants.typoscript
Due to a wrong `!default` specification the `custom-select-indicator` in a `custom-select` was not displayed.
Removing the wrong specification fixes this.
> Fix `custom-select-indicator`

- Classes/Updates/AccordionContentElementUpdate.php
- Classes/Updates/AccordionMediaOrientUpdate.php
- Classes/Updates/BackendLayoutUpdate.php
- Classes/Updates/BulletContentElementUpdate.php
- Classes/Updates/CarouselContentElementUpdate.php
- Classes/Updates/CarouselItemTypeUpdate.php
- Classes/Updates/ExternalMediaContentElement.php
- Classes/Updates/ForcedUpdate.php
- Classes/Updates/FrameClassToBackgroundUpdate.php
- Classes/Updates/ListGroupContentElement.php
- Classes/Updates/PanelContentElementUpdate.php
- Classes/Updates/TabContentElementUpdate.php
- Classes/Updates/TabMediaOrientUpdate.php
- Classes/Updates/TableContentElementUpdate.php
- Classes/Updates/TexticonContentElement.php
- Classes/Updates/TexticonIconUpdate.php
- Classes/Updates/TexticonSizeUpdate.php
- Classes/Updates/TexticonTypeUpdate.php
Fixes #719
Backport for TYPO3 8.7 compatibility
This PR is not applicable for TYPO3 master, an other aproach will be used there see #720
> [BUGFIX] Make UpgradeWizards repeatable

- Build/Gruntfile.js
- Resources/Public/JavaScript/Dist/bootstrap.accordion.min.js
- Resources/Public/JavaScript/Src/bootstrap.accordion.js
Fixes  #774
1. add Bootstrap 4 collapse/accordion example https://getbootstrap.com/docs/4.3/components/collapse/#accordion-example to any page 
2. open/close it
3. without patch: JavaScript error
> [BUGFIX] Resolve plain bootstrap 4 accordion conflicts

- .github/labeler.yml
- .github/workflows/label.yml
This patch activates the labeler action for pull request and defines the files containing dependencies to get the dependencies label added automatically.
> [TASK] Automatically label dependency changes

- composer.json
This conflict is not needed because of the raised dependency in #764.
> [TASK] Remove scssphp/scssphp conflict

- composer.json
For me it looks like the dependency for `typo3fluid/fluid` is missing in composer e.g. the InlineSvgViewHlper is requiring the `TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper`.
https://github.com/benjaminkott/bootstrap_package/blob/master/Classes/ViewHelpers/InlineSvgViewHelper.php#L17
It can be that most people have the `typo3fluid/fluid` include in their projects, but as it's used here directly it should in my opinion be a hard dependency.
> [TASK] Add typo3fluid/fluid to composer dependencies

- Configuration/TypoScript/Helper/PageClass.typoscript
**TSFE:sys_language_uid** is marked deprecated since TYPO3 v9.4 and **siteLanguage:twoLetterIsoCode** or **siteLanguage:languageId** should be used.
This patch fix the missing class for the current  language in body tag.
1. Visit [www.bootstrap-package.com](https://www.bootstrap-package.com/)
2. Open the Inspector or check the page source code (body tag)
> [BUGFIX] Missing body class for current language

- ext_localconf.php
See deprecation #85462 (https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85462-SignalHasInstalledExtensions.html)
> [TASK] Migrate to afterExtensionInstall signal

- Resources/Private/Templates/ContentElements/Uploads.html
This reverts commit 826f6beb431853a5f396917cb2d20f3a29ac6c70.
This issue was caused by wrong database entries which can be solved by removing the assets in the admin tool. Clearing the caches only does not help here.
> Revert "[BUGFIX] Use image vh for image types to enable thumbnails for non images like PDF files (#913)"

- Classes/Parser/ScssParser.php
- Tests/Unit/Compiler/Fixtures/Calculation/Output.css
* Fixes #947
This patch fixes our own scss import behavior with the latest changes at scssphp/scssphp version 1.4. Also the expectation of the CSS output is fixed.
Run the functional tests with scssphp 1.4 and a lower release e.g. 1.3
The unit tests will fail with versions lower than 1.4 because of an other fix in scssphp 1.4.
> [BUGFIX] Apply latest scssphp changes to import behavior

- Configuration/Form/Setup.yaml
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87009-UseMultipleTranslationFilesByDefaultInEXTform.html
and https://review.typo3.org/c/Packages/TYPO3.CMS/+/65842
> [BUGFIX] Update form definition

- .github/workflows/ci.yml
- .github/workflows/publish.yml
Merging changes to forks leads to workflow errors and these new conditions avoid it.
> [TASK] Disable deployment and publish workflows for forks

- Resources/Public/Scss/bootstrap5/compat/_form.scss
SassError: compound selectors may no longer be extended. Consider `@extend .form-control, .is-invalid` instead. See: https://sass-lang.com/documentation/breaking-changes/extend-compound for details.
> [BUGFIX] SassError: compound selectors may no longer be extended.

- Build/phpstan-baseline.neon
- Configuration/TypoScript/Bootstrap5/constants.typoscript
The constant `font-family-monospace` has a `!default` appended which breaks its usage in browsers.
This patch removes the declaration.
1. Insert `<code>foo</code>` with RTE
2. Check the frontend rendering
3. The rendered `<code>` uses a sans-serif font
> [BUGFIX] Remove wrong !default from monospace

- Resources/Public/Scss/bootstrap5/compat/_form.scss
Reverts benjaminkott/bootstrap_package#1023
> [REVERT][BUGFIX] SassError: compound selectors may no longer be extended.

- Classes/ViewHelpers/InlineSvgViewHelper.php
The function dom_import_simplexml no longer returns null on failure with php 8.0.
> [BUGFIX] Ignore phpstan error for dom_import_simplexml

- Configuration/TCA/Overrides/300_content_general_columns.php
With the change https://review.typo3.org/c/Packages/TYPO3.CMS/+/70177
using rtehtmlarea_images in the softref config is not longer possible.
> [BUGFIX] Remove external softref to ext:rtehtmlarea

- Configuration/TCA/tx_bootstrappackage_accordion_item.php
- Configuration/TCA/tx_bootstrappackage_card_group_item.php
- Configuration/TCA/tx_bootstrappackage_carousel_item.php
- Configuration/TCA/tx_bootstrappackage_icon_group_item.php
- Configuration/TCA/tx_bootstrappackage_tab_item.php
- Configuration/TCA/tx_bootstrappackage_timeline_item.php
With the change https://review.typo3.org/c/Packages/TYPO3.CMS/+/70177
using images in the softref config is not longer possible.
> [BUGFIX] Remove deprecated softref `images`

- Configuration/RTE/Default.yaml
* Fixes #728 
Fixes wrong classes for table rows (tr) and adds classes for table data cells (td)
1. Go to page Congratulations->Content Examples->Text->Rich Text
2. Edit content element "Tables"
3. Select styles for table rows and cells
> [BUGFIX] Wrong table classes and add missing ones

- .ddev/commands/web/build
- .ddev/commands/web/npm
This patch introduces two custom commands for DDEV to simplify the frontend related processes.
Runs npm in the `Build` folder in the web container. Parameters are passed to npm. See also `ddev npm -h`.
Runs a script in the `Build` folder in the web container. Before the script is executed a `npm install` is performed which can be skipped by adding the `--no-install` option. Default script is `build` or provide the script name as parameter. See also `ddev build -h`.
> [TASK] Provide frontend build custom commands

- Classes/Service/BrandingService.php
With the commit https://github.com/benjaminkott/bootstrap_package/commit/4ccae72be1b639030f78af248daa47f62c752162 the conditions were accidentially inverted.
> [BUGFIX] BrandingService conditions

- Classes/Utility/SvgUtility.php
See also https://github.com/TYPO3/typo3/commit/0a39476561e77e9bcb3786fcc973d4a49af41783.
Fixes #1104
> [BUGFIX] Do not call "libxml_disable_entity_loader" in PHP 8

- Configuration/TCA/Overrides/600_ext_container.php
- Resources/Private/Language/Backend.xlf
Labels in Ext:Container configuration are hardcoded
With this pull request, a translation option becomes easier
* [x ] Changes have been tested on TYPO3 v11.5 LTS
* [ x] Changes have been tested on PHP 7.4.x
* [ x] Changes have been checked for CGL compliance `php-cs-fixer fix`
Changed TCA and Backend.xlf
> [FEATURE] Use translatable labels for container names and columns

- Configuration/Services.yaml
After installing bootstrap_package on TYPO3 v12, dependency injection is now able to find its classes.
It's related to this change https://review.typo3.org/c/Packages/TYPO3.CMS/+/72469
> [BUGFIX] Register classes in DI container for TYPO3 v12

- Documentation/Introduction/Index.rst
Hi Benjamin, 
isn't the bootstrap_package based on bootstrap 5.1?
Best regards
Eckard.
* Closes #
> [BUGFIX]  Correct Bootstrap version in docu

- Configuration/TCA/tx_bootstrappackage_carousel_item.php
$GLOBALS['TYPO3_CONF_VARS']['BE']['explicitADmode'] does
not exist anymore. Fall back to old default for <v12
compatibility. See [1] for details.
[1] https://forge.typo3.org/issues/97265
> [BUGFIX] Avoid early fatal with TYPO3 v12

- Classes/Backend/ToolbarItem/VersionToolbarItem.php
Third argument $returnValue of CommandUtility::exec() has been
type hinted to int in [1]. bootstrap_package fails now since
it uses a not initialized variable. Init properly.
[1] https://forge.typo3.org/issues/97206
* Closes #
> [BUGFIX] Avoid unitialized variable in VersionToolbarItem

- Classes/DataProcessing/ContainerContextProcessor.php
I get this error in TYPO3 v11, bootstrap_package v12.0.5 when using PHP 8.1:
```
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Runtime Deprecation Notice: Automatic conversion of false to array is deprecated in /var/www/html/public/typo3conf/ext/bootstrap_package/Classes/DataProcessing/ContainerContextProcessor.php line 73
```
A quick debug revealed that the getter in line 63 in ContainerContextProcessor.php returns false:
`$cache = $runtimeCache->get('containerContext') ?? [];`
The shorthand ternary operator can solve this.
`$cache = $runtimeCache->get('containerContext') ?: [];`
1. Setup TYPO3 v11 with PHP 8.1
2. Install bootstrap_package and containers via composer
3. Use container content element on any page
> [BUGFIX] Change null coalesce operator to long ternary operator

- Classes/Userfuncs/Tca.php
PHP Warning: Undefined array key "header" and PHP Warning: Undefined array key "date"
* Closes #
> [BUGFIX] Prevent PHP Warning: Undefined array key

- .github/workflows/ci.yml
- .github/workflows/publish.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> [TASK] Replace deprecated set-output command

- Configuration/TCA/tx_bootstrappackage_accordion_item.php
- Configuration/TCA/tx_bootstrappackage_card_group_item.php
- Configuration/TCA/tx_bootstrappackage_carousel_item.php
- Configuration/TCA/tx_bootstrappackage_icon_group_item.php
- Configuration/TCA/tx_bootstrappackage_tab_item.php
- Configuration/TCA/tx_bootstrappackage_timeline_item.php
"Item" records provided by EXT:bootstrap_package (e.g. for accordion, carousel, etc.) are usually rendered in IRRE contexts. There is a wild bug if an element is disabled ("hidden") that makes it very hard to enable it again.
The root cause is that checkbox fields are internally handled as bitmasks, triggering a strange behavior as an enabled checkbox is rendered as disabled as long the element is disabled.
To overcome this issue until TYPO3 Core's behavior is fixed, "hidden" fields are now rendered as `checkboxToggle` that don't trigger the bug.
> [BUGFIX] Render "hidden" fields as `checkboxToggle`

- Classes/ViewHelpers/Data/ImageVariantsViewHelper.php
- Classes/ViewHelpers/Format/TrimViewHelper.php
* Fixes #1217
* [x ] Changes have been tested on TYPO3 v11.5 LTS
* [x ] Changes have been tested on PHP 8.0
Assign sane fallback values using the coalesce operator.
1. See related issue
> [BUGFIX] Fix undefined variables access (PHP 8+ compatibility)

- Configuration/TypoScript/ContentElement/Helper/ContentElement.typoscript
- Configuration/TypoScript/ContentElement/constants.typoscript
Add the missing no-cookie option for media (youtube and vimeo) and enabled it by default.
> [BUGFIX] Add missing no-cookie to media additionalConfig

- Classes/Utility/ImageVariantsUtility.php
- Tests/Unit/Utility/ImageVariantsUtilityTest.php
* Fixes  #1261  [bug]
On Versions 12 and 13: Remove line 117 from ImageVariantsUtility.php, the line 119 is already casting the multiplier value to the correct type.
Both versions above have the same line and can be removed:
$settings['multiplier'] = gettype($settings['multiplier']) === 'double' ? $settings['multiplier'] : (int) $settings['multiplier'];
1. Add a TypoScript setup as shown in the [documentation](https://docs.typo3.org/p/bk2k/bootstrap-package/main/en-us/Configuration/ImageRendering/Index.html#high-resolution-images) (inlined for brevity):
`lib.contentElement.settings.responsiveimages.variants.default.sizes.1\.5x.multiplier = 1.5`
2. Add an image element to any webpage. You can skip this if you already have an image element to check.
3. Inspect the image source code in the …
> Fix multiplier value float type being transformed to integer.

- Classes/Icons/FileIcon.php
- Classes/Utility/SvgUtility.php
Related: #1278
* Fixes #1278
More Doc here: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden
@benjaminkott and @alboth decided that all ICONs on the can be interpreted as purely decorative content. 
Therefor they all deserve a ``¸`aria-hidden="true"`
It is fixed for 
- Fileicons (png, svg)
- Ionicons & Glypicons (using SvgUtility)
In my opinion we could still debate/think about the bootstrap icon-font. The `[::before](bootstrappackageicon::before)` have no css `speak: none` property.  
1. co branch 1278-aria-hidden-for-decorative-images
2. visit in ticket mentioned urls - https://github.com/benjaminkott/bootstrap_package/issues/1278
3. check that other images DO NOT get the `aria-hidden` attribute
> [TASK] Add aria-hidden attributes for decorative icons

- Configuration/Form/Setup.yaml
* Fixes #1313
TASK: Remove roles "group" and "toolbar" from contact form submit button.
SOLUTION: Switch to new form templates ("version2") which do not contain these roles in the markup
see: https://forge.typo3.org/issues/95456
1. Add predefined contact form to any page
2. Check form markup in frontend
> [TASK] Switched forms template variant to version2

- Resources/Private/Partials/Page/Navigation/Breadcrumb.html
Ref: #1326
Only last item gets aria-current
Got to page https://bitv-v12.live.typo3.cps.321.works/content-examples/text/rich-text ,and "Text" in breadcrump should not have aria-current
> [TASK] only use aria-current for the last item in breadcrumb

- Classes/Parser/AbstractParser.php
- Classes/Parser/ScssParser.php
- Tests/Functional/Parser/ScssParserTest.php
The source maps are no longer inlined in the compiled CSS file. There‘s a .css.map file for the compiled CSS file instead. Sources are now included into the map file. This means that sources can now be moved to non-public folders without losing the possibility to debug your code.
Related: #1263
* Closes #
> [BUGFIX] Source mapping is now public path agnostic

- Resources/Private/Templates/ContentElements/Tab.html
* Resolves #1295
Replace nav tag with div tag in Template CustomElements/Tab.html
1. Go to page https://bitv-v12.live.typo3.cps.321.works/content-examples/interactive/tab
2. Check that the tab menu no longer contains a nav tag
> [TASK] replace nav tag with div tag in custom element tab

- Resources/Private/Language/locallang.xlf
- Resources/Private/Partials/Page/Navigation/Main.html
- Resources/Private/Partials/Page/Navigation/Subnavigation.html
Related: #1291
* Closes #
* Related #1291
Aria-Labels added for main and subnavigation as descirbed in ticket #1291
1. pull
2. open page: https://bootstrap-package.ddev.site/content-examples/text/bullet-list
3. check if aria-label can be found on main and sub-navigatin (=in aside column)
> [TASK] Add aria-labels for main and sub navigation

- Classes/Utility/TcaUtility.php
- Configuration/TCA/Overrides/201_content_element_audio.php
- Configuration/TCA/Overrides/207_content_element_csv.php
- Configuration/TCA/Overrides/213_content_element_media.php
- Tests/Unit/Utility/TcaUtilityTest.php
–
With TYPO3 v12.0, a new TCA type [`file`](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-98479-NewTCATypeFile.html) was introduced. This type is used for the `tt_content.media` and `tt_content.assets` fields. Thus, all columns overrides for TYPO3 v12 must match the new TCA config.
This PR solves an issue with columns overrides of media columns concerning allowed file extensions. With the new TCA type, the expected TCA config looks different. In order to solve this issue and still support the previous behavior for TYPO3 v11.5, a new `TcaUtility` class is introduced. It returns a valid TCA config for allowed and/or disallowed file extensions, depending on the current TYPO3 version.
1. Create a new content element of type "Audio" or "Media" in TYPO3 v11.5
2. …
> [BUGFIX] Handle allowed file extensions for TYPO3 v12

- Resources/Private/Partials/ContentElements/Media/Rendering/Image.html
* Closes #
intrinsicsize was a suggested attribute for all HTML media elements and was previously implemented by Google Chrome. However, it wasn't implemented by any other browser because height/width are now used to calculate the initial aspect ratio.
Explanation: https://github.com/WICG/intrinsicsize-attribute/issues/16
Chrome status: https://chromestatus.com/feature/4704436815396864
> [TASK] Remove obsolete intrinsicsize attribute

- Classes/Utility/ExternalMediaUtility.php
- Classes/ViewHelpers/ExternalMediaViewHelper.php
- Configuration/TCA/Overrides/208_content_element_externalmedia.php
- Resources/Private/Language/Backend.xlf
- Resources/Private/Templates/ContentElements/ExternalMedia.html
- Resources/Private/Templates/Preview/ExternalMedia.html
- Tests/Unit/Utility/ExternalMediaUtilityTest.php
- ext_tables.sql
* Resolves #1296
Problem:
All frames should have a title attribute containing information about the frame's content. Currently, iframes with YouTube videos are only labelled with the video's title.
Solution:
Add new field to external media content element to assign an iframe title.
1. Create a "External Media" content element on any page and fill out "External Media iframe title"
2. Open page in the frontend and check iframe markup
3. Title attribute should be set
> [TASK] Add new external media field to assign an iframe title (#1296)

- Configuration/FlexForms/Accordion.xml
- Configuration/FlexForms/BackgroundImage.xml
- Configuration/FlexForms/CardGroup.xml
- Configuration/FlexForms/Carousel.xml
- Configuration/FlexForms/IconGroup.xml
- Configuration/FlexForms/MenuCard.xml
- Configuration/FlexForms/MenuThumbnail.xml
- Configuration/FlexForms/Tab.xml
- Configuration/FlexForms/Timeline.xml
Using TCEforms within flexform definitions has been deprecated in v12 and removed in v13:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97126-TCEformsRemovedInFlexForm.html
This patch is compatible to v12 and v13 by removing this element.
(Otherwise, in v13, all flexform options would not be editable)
1. In v13, create an carousel item. 
2. Check the flexform options in Tab "Carousel Options".
3. See that all option keys are listed, but no labels and inputs
> [TASK] Remove deprecated TCEforms flexform XML element

- .editorconfig
- Classes/ExpressionLanguage/ConditionProvider.php
- Classes/ExpressionLanguage/ExtensionConfigurationWrapper.php
- Configuration/page.tsconfig
- ext_localconf.php
Register own condition matcher to access ExtensionConfiguration toggles. Switch from INCLUDE_TYPOSCRIPT to @import.
> [TASK] Avoid deprecated EMU::addPageTSConfig()

- Configuration/Sets/Full/settings.definitions.yaml
Probably a copy-paste issue - all template root paths pointed to the partials folder. I can't currently test it but looking at originating commit https://github.com/benjaminkott/bootstrap_package/commit/01ed74bd8df1715d9dc2ce0c9aa30cf51ba8ae3e#diff-ddd1bfabb1769af3a562fa387512a32d01c80b3285bbbce9f5db5d1f4c11d83b the old code always pointed to .../Templates/
> Updated templateRootPath folders

- Build/phpunit-functional.xml
- Build/phpunit-unit.xml
- Tests/Unit/Compiler/ScssCompilerTest.php
- Tests/Unit/DataProcessing/SkiplinkProcessorTest.php
- Tests/Unit/Utility/ExternalMediaUtilityTest.php
- Tests/Unit/Utility/ImageVariantsUtilityTest.php
Updating PHPUnit configuration files and migrate tests from annotations to attributes.
> [TASK] Remove PHPUnit deprecations
